print("risky stacking")
print("==============")
height_of_one_chair = input("Enter_the_height_of_one_chair: ")
print("")
height_of_overall_chair_tower = input("Enter_the_height_of_overall_chair_tower: ")
print("")
print("the total number of chairlegs in the tower is: <<totalnumberofchairlegsintower>>")
